export const categoryTitles = {
  "web-development": "Web Development",
  "website-design-development": "Website Design & Development",
  "ui-ux-design": "UI/UX Design",
  "graphic-design": "Graphic Design",
  "ecommerce": "E-commerce",
  "modern-responsive-websites": "Modern & Responsive Websites",
  "digital-marketing": "Digital Marketing",
  "digital-marketing-seo": "Digital Marketing & SEO",
  "social-media": "Social Media",
  "social-media-management": "Social Media Management",
  "influencer-marketing": "Influencer Marketing",
  "artificial-intelligence": "Artificial Intelligence",
  "machine-learning": "Machine Learning",
  "cybersecurity": "Cybersecurity",
  "data-analytics": "Data Analytics",
  "seo": "SEO",
  "visual-production": "Visual Production",
  "creative-content": "Creative Content",
  "other": "Other",
};
